//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> CatID { get; set; }
        public Nullable<long> BasePrice { get; set; }
        public Nullable<long> SellPrice { get; set; }
        public Nullable<long> InventoryNum { get; set; }
        public byte[] AvatarImage { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
