//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVE
    {
        public long ID { get; set; }
        public long No_ { get; set; }
        public Nullable<long> CakeID { get; set; }
        public Nullable<long> CakeNum { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> TotalBill { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual CAKE CAKE { get; set; }
    }
}
